services:
  db:
    image: postgres:16.2
    container_name: db_todo_list
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist_db
    volumes:
      - ./.data/db:/var/lib/postgresql/data